### ISSUE TITLE
Word that doesn't exist (in RAE) causes infinite loop

### ISSUE THREAD

**Issue by puhrez** [lsvx/drae#3]
```
$ drae define astrolabiodo
panic: Get http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/http://dle.rae.es/srv/search?w=astrolabiodo: read tcp 192.168.1.37:65046->85.62.86.187:80: read: connection reset by peer

goroutine 1 [running]:
panic(0x28c720, 0xc420408210)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.Scrape(0xc420987000, 0x17f9, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:22 +0x3f3
main.Scrape(0xc420993000, 0x17e3, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42099b800, 0x17cd, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42099a000, 0x17b7, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420990000, 0x17a1, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420984000, 0x178b, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420979000, 0x1775, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420976000, 0x175f, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42096e000, 0x1749, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42095f000, 0x1733, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420953000, 0x171d, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42095c000, 0x1707, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420947000, 0x16f1, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420950000, 0x16db, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42093f000, 0x16c5, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420945800, 0x16af, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42093c000, 0x1699, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420933800, 0x1683, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42090a800, 0x166d, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420910800, 0x1657, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42090f000, 0x1641, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4206ad800, 0x162b, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42088c800, 0x1615, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42090c000, 0x15ff, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420907800, 0x15e9, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208f0800, 0x15d3, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208f5000, 0x15bd, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420889800, 0x15a7, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420888000, 0x1591, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208b3000, 0x157b, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208b0000, 0x1565, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4200a2800, 0x154f, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208f9800, 0x1539, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208f8000, 0x1523, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4200a1000, 0x150d, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208d8000, 0x14f7, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208caa00, 0x14e1, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208cd500, 0x14cb, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208c8000, 0x14b5, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42089ca00, 0x149f, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42089b500, 0x1489, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42089a000, 0x1473, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420896000, 0x145d, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420707500, 0x1447, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420706000, 0x1431, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42087b500, 0x141b, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42067a000, 0x1405, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208d4a00, 0x13ef, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42077ca00, 0x13d9, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420894a00, 0x13c3, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208baa00, 0x13ad, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208aaa00, 0x1397, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208b8000, 0x1381, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208bea00, 0x136b, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208d2000, 0x1355, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208c1500, 0x133f, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208c0000, 0x1329, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208b9500, 0x1313, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208a6a00, 0x12fd, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208aea00, 0x12e7, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208a2a00, 0x12d1, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208ac000, 0x12bb, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208a9500, 0x12a5, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208a4000, 0x128f, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4208a0000, 0x1279, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42070ea00, 0x1263, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420893500, 0x124d, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42077b500, 0x1237, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42070c000, 0x1221, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420026a00, 0x120b, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420883200, 0x11f5, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420846800, 0x11df, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42071b600, 0x11c9, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42071a400, 0x11b3, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420719200, 0x119d, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420718000, 0x1187, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420875200, 0x1171, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420844400, 0x115b, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420851600, 0x1145, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42086d600, 0x112f, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42084e000, 0x1119, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4205fc800, 0x1103, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420874000, 0x10ed, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42086a000, 0x10d7, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42083c800, 0x10c1, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42083b600, 0x10ab, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42084f200, 0x1095, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420839200, 0x107f, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420842000, 0x1069, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420838000, 0x1053, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4205fb600, 0x103d, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4201ad600, 0x1027, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4205ed600, 0x1011, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42081c000, 0xffb, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420816000, 0xfe5, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc42080e000, 0xfcf, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420808000, 0xfb9, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc420804000, 0xfa3, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
main.Scrape(0xc4207fb000, 0xf8d, 0x7fff5fbff83e, 0xc, 0x0, 0x0, 0x0)
    /Users/micperez/code/src/github.com/lsvx/drae/scrape.go:48 +0x284
...additional frames elided...
```

happens at of this line: https://github.com/squat/drae/blob/master/scrape.go#L48
probably because this assumption, https://github.com/squat/drae/blob/master/scrape.go#L33, 
doesn't hold true: http://dle.rae.es/srv/search?w=astrolabiodo

**Comment by squat** [comment]
Yes, thanks for filing this issue! I just fixed this in the rewrite. It was because the scraper assumed that if the word wasn't found it was because there was a dissbiguation page with links, which is obviously not always the case.
